#!/bin/bash

. /etc/init.d/functions.sh
. /etc/kerninst/kerninst.conf

function termtitle() {
    echo -ne "\x1b]0;${1}\x07" > /dev/stderr
}

function kerror() {
    termtitle "${1}"
    eerror "${1}"
}

function kinfo() {
    termtitle "${1}"
    einfo "${1}"
}

LOGFILE=/var/log/kerninst.log

/bin/rm -f "${LOGFILE}"

if [ ! -L /usr/src/linux ]; then
    kerror "The symbolic link /usr/src/linux does not exists."
    exit 1
fi

KERNEL_DIR=$(readlink /usr/src/linux)
MACHINE_ID=$(cat /etc/machine-id)

if [ ! -d "/usr/src/${KERNEL_DIR}" ] || [ ! -f "/usr/src/${KERNEL_DIR}/Makefile" ]; then
    if [ ! grep -q KBUILD "/usr/src/${KERNEL_DIR}/Makefile" ]; then
        kerror "The file /usr/src/${KERNEL_DIR} is not a valid kernel directory."
        exit 1
    fi
fi

KERNEL_VERSION=$(readlink /usr/src/linux | sed "s/^linux-//g")

if [ "${KERNEL_VERSION}" == "" ] || [[ "${KERNEL_VERSION}" =~ \ |\' ]]; then
    kerror "The version ${KERNEL_VERSION} is not a valid kernel version."
    exit 1
fi

function die() {
    kerror "An error ocurred. Exiting."
    exit 1
}

function kernel_compile() {
    kinfo "Copying kernel configuration from ${KERNEL_CONFIG}..."
    /bin/cp -f "${KERNEL_CONFIG}" /usr/src/linux/.config &>> "${LOGFILE}" || die

    kinfo "Configuring kernel..."
    /bin/yes "" | make -C /usr/src/linux oldconfig &>> "${LOGFILE}" || die

    if [ "${UPDATE_KERNEL_CONFIG}" == "yes" ]; then
        kinfo "Updating kernel config..."
        /bin/cp -f /usr/src/linux/.config "${KERNEL_CONFIG}" || die
    fi

    kinfo "Compiling kernel..."
    /usr/bin/make ${KERNEL_MAKEOPTS} -C /usr/src/linux &>> "${LOGFILE}" || die
}

function _delete_kernel_files_grub() {
    kinfo "Deleting kernel files with version ${KERNEL_VERSION} from /boot..."
    /bin/rm -f "/boot/config-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f "/boot/initrd-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f "/boot/System.map-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f "/boot/vmlinuz-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
}

function _delete_kernel_files_bootctl() {
    kinfo "Deleting kernel files with version ${KERNEL_VERSION} from /boot..."
    /bin/rm -rf "/boot/${MACHINE_ID}/${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f \
        "/boot/loader/entries/${MACHINE_ID}-${KERNEL_VERSION}.conf" &>> "${LOGFILE}" || die
}

function _delete_lib_modules() {
    kinfo "Deleting kernel files with version ${KERNEL_VERSION} from /lib/modules..."
    /bin/rm -rf "/lib/modules/${KERNEL_VERSION}" &>> "${LOGFILE}" || die
}

function _delete_kernel_files() {
    case "${BOOT_MANAGER}" in
        grub)
            _delete_kernel_files_grub
            ;;
        bootctl)
            _delete_kernel_files_bootctl
            ;;
        *)
            kerror "Invalid boot manager."
            ;;
    esac
    _delete_lib_modules
}

function _install_modules() {
    kinfo "Installing modules..."
    make -C /usr/src/linux modules_install &>> "${LOGFILE}" || die
}

function kernel_install() {
    _delete_kernel_files
    case "${BOOT_MANAGER}" in
        grub)
            kernel_install_grub
            ;;
        bootctl)
            kernel_install_bootctl
            ;;
        *)
            kerror "Invalid boot manager."
            ;;
    esac
    _install_modules
}

function kernel_install_grub() {
    kinfo "Installing kernel..."
    make -C /usr/src/linux install &>> "${LOGFILE}" || die
    kinfo "The kernel was installed into /boot/vmlinuz-${KERNEL_VERSION}."
}

function kernel_install_bootctl() {
    LOCATION="/boot/${MACHINE_ID}/${KERNEL_VERSION}/kernel"

    kinfo "Installing kernel..."
    /bin/mkdir -p "/boot/${MACHINE_ID}/${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    cp "/usr/src/linux/arch/x86/boot/bzImage" "${LOCATION}" &>> "${LOGFILE}" || die
    kinfo "The kernel was installed into ${LOCATION}."
}

function _initrd_location() {
    case "${BOOT_MANAGER}" in
        grub)
            echo "/boot/initrd-${KERNEL_VERSION}"
            ;;
        bootctl)
            echo "/boot/${MACHINE_ID}/${KERNEL_VERSION}/initrd"
            ;;
        *)
            echo ""
            ;;
    esac
}

function make_initrd() {
    if [ "${MODULES_REBUILD}" == "yes" ]; then
        kinfo "Recompiling modules..."
        /usr/bin/emerge -v @module-rebuild &>> "${LOGFILE}" || die
    fi

    LOCATION=$(_initrd_location)
    if [ "${LOCATION}" == "" ]; then
        kerror "Invalid boot manager."
    fi

    kinfo "Creating initrd..."
    if [ "${INCLUDES}" != "" ] || [ "${INCLUDE_FIRMWARE}" == "yes" ]; then
        INCLUDED="-I"

        for i in $(find /lib64/firmware -type f); do
            INCLUDED+=" ${i}"
        done

        for i in $(echo ${INCLUDES}); do
            INCLUDED+=" ${i}"
        done

        /usr/bin/dracut -f "${INCLUDED}" "${LOCATION}" "${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    else
        /usr/bin/dracut -f "${LOCATION}" "${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    fi
    kinfo "The initrd was installed into ${LOCATION}."
}

function update_bootmanager_grub2() {
    kinfo "Updating GRUB2..."
    if [ "${MOUNT_BOOT_EFI}" == "yes" ]; then
        kinfo "Mounting EFI boot directory..."
        /bin/mountpoint -q  /boot/efi || /bin/mount /boot/efi
    fi
    /usr/sbin/grub2-mkconfig -o "${GRUB2_CONFIG_FILE}" &>> "${LOGFILE}" || die
}

function update_bootmanager_bootctl() {
    kinfo "Updating Bootctl..."
    if [ "${BOOTCTL_TITLE}" == "" ]; then
        BOOTCTL_TITLE="Linux"
    fi

    ENTRY="/boot/loader/entries/${MACHINE_ID}-${KERNEL_VERSION}.conf"
    KERNEL="/${MACHINE_ID}/${KERNEL_VERSION}/kernel"
    INITRD="/${MACHINE_ID}/${KERNEL_VERSION}/initrd"

    /usr/bin/printf "title\t\t%s\n" "${BOOTCTL_TITLE}"        > ${ENTRY}
    /usr/bin/printf "version\t\t%s\n" "${KERNEL_VERSION}"      >> ${ENTRY}
    /usr/bin/printf "machine-id\t%s\n" "${MACHINE_ID}"         >> ${ENTRY}
    /usr/bin/printf "linux\t\t%s\n" "${KERNEL}"                >> ${ENTRY}
    /usr/bin/printf "initrd\t\t%s\n" "${INITRD}"               >> ${ENTRY}
    /usr/bin/printf "options\t\t%s\n" "${KERNEL_COMMAND_LINE}" >> ${ENTRY}
    if [ "${BOOTCTL_SPLASH}" != "" ]; then
        /usr/bin/printf "splash\t\t%s\n" "${BOOTCTL_SPLASH}" >> ${ENTRY}
    fi
}

function update_bootmanager() {
    case "${BOOT_MANAGER}" in
        grub)
            update_bootmanager_grub2
            ;;
        bootctl)
            update_bootmanager_bootctl
            ;;
        *)
            kerror "Invalid boot manager."
            ;;
    esac
}

EXEC_NAME=$(/usr/bin/basename "$0")

for ARG in "$@"; do
    case "${ARG}" in
        --modules-rebuild)
            MODULES_REBUILD="yes"
            ;;
        --no-modules-rebuild)
            MODULES_REBUILD="no"
            ;;
        --update-kernel-config)
            UPDATE_KERNEL_CONFIG="yes"
            ;;
        --no-update-kernel-config)
            UPDATE_KERNEL_CONFIG="no"
            ;;
    esac
done

function _delete_other_files_grub() {
    for FILE in /boot/{config,initrd,System.map,vmlinuz}-*; do
        if [ "${FILE}" == "/boot/config-${KERNEL_VERSION}" ] ||
               [ "${FILE}" == "/boot/initrd-${KERNEL_VERSION}" ] ||
               [ "${FILE}" == "/boot/System.map-${KERNEL_VERSION}" ] ||
               [ "${FILE}" == "/boot/vmlinuz-${KERNEL_VERSION}" ]; then
            continue
        fi
        kinfo "Deleting ${FILE}..."
        /bin/rm -f "${FILE}" &>> "${LOGFILE}" || die
    done
}

function _delete_other_files_bootctl() {
    for DIR in /boot/${MACHINE_ID}/*; do
        if [ "${DIR}" == "/boot/${MACHINE_ID}/${KERNEL_VERSION}" ]; then
            continue
        fi
        kinfo "Deleting ${DIR}..."
        /bin/rm -rf "${DIR}" &>> "${LOGFILE}" || die
    done
    for FILE in /boot/loader/entries/*; do
        if [ "${FILE}" == "/boot/loader/entries/${MACHINE_ID}-${KERNEL_VERSION}.conf" ]; then
            continue
        fi
        kinfo "Deleting ${FILE}..."
        /bin/rm -f "${FILE}" &>> "${LOGFILE}" || die
    done
}

function clean() {
    for DIR in /usr/src/linux-* /lib/modules/*; do
        if [ ! -d "${DIR}" ]; then
            continue
        fi
        if [ "${DIR}" == "/usr/src/${KERNEL_DIR}" ]; then
            continue
        fi
        if [ "${DIR}" == "/lib/modules/${KERNEL_VERSION}" ]; then
            continue
        fi
        kinfo "Deleting ${DIR}..."
        /bin/rm -rf "${DIR}" &>> "${LOGFILE}" || die
    done
    case "${BOOT_MANAGER}" in
        grub)
            _delete_other_files_grub
            ;;
        bootctl)
            _delete_other_files_bootctl
            ;;
        *)
            kerror "Invalid boot manager."
            ;;
    esac
}

case "${EXEC_NAME}" in
    kerninst)
        kernel_compile
        kernel_install
        make_initrd
        update_bootmanager
        ;;
    kerninst-compile)
        kernel_compile
        ;;
    kerninst-install)
        kernel_install
        ;;
    kerninst-mkinitrd)
        make_initrd
        ;;
    kerninst-updatebm)
        update_bootmanager
        ;;
    kerninst-clean)
        clean
        ;;
    *)
        kerror "Invalid executable name."
        ;;
esac
