#!/bin/bash

# Copyright © 2016-2017 Canek Peláez Valdés

# Kerninst is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.

# Kerninst is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with
# kerninst. If not, see <http://www.gnu.org/licenses/>.

# Author:
#  Canek Peláez Valdés <canek@ciencias.unam.mx>

# kerninst: Compile and install a kernel in Gentoo. Also, create and install an
# initrd created with dracut, and configure either Grub or Bootctl to use the
# new kernel and associated initrd.

# Pretty messages
. /etc/init.d/functions.sh
# Configuration
. /etc/kerninst/kerninst.conf

# Set the terminal title
function termtitle() {
    echo -ne "\x1b]0;${1}\x07" > /dev/stderr
}

# Print an error and exit
function kerror() {
    termtitle "${1}"
    eerror "${1}"
    exit 1
}

# Print information and exit
function kinfo() {
    termtitle "${1}"
    einfo "${1}"
}

# Log file
LOGFILE=/var/log/kerninst.log

# Delete old log file
/bin/rm -f "${LOGFILE}"

# Chech for kernel directory symbolic link
if [ ! -L /usr/src/linux ]; then
    kerror "The symbolic link /usr/src/linux does not exists."
fi

# Kernel directory
KERNEL_DIR=$(readlink /usr/src/linux)
# Machine ID
MACHINE_ID=$(cat /etc/machine-id)

# Check that the kernel directory is valid
if [ ! -d "/usr/src/${KERNEL_DIR}" ] || [ ! -f "/usr/src/${KERNEL_DIR}/Makefile" ]; then
    if [ ! grep -q KBUILD "/usr/src/${KERNEL_DIR}/Makefile" ]; then
        kerror "The file /usr/src/${KERNEL_DIR} is not a valid kernel directory."
    fi
fi

# Get kernel version from symbolic link
KERNEL_VERSION=$(readlink /usr/src/linux | sed "s/^linux-//g")

# Check for a valid kernel version
if [ "${KERNEL_VERSION}" == "" ] || [[ "${KERNEL_VERSION}" =~ \ |\' ]]; then
    kerror "The version ${KERNEL_VERSION} is not a valid kernel version."
fi

# Check for a valid boot manager
if [ "${BOOT_MANAGER}" != "grub" ] && [ "${BOOT_MANAGER}" != "bootctl" ]; then
    kerror "Invalid boot manager."
fi

# Returns the necessary boot subdir, depending on the boot manager
function _bootsubdir() {
    case "${BOOT_MANAGER}" in
        grub)
            echo "/boot/grub"
            ;;
        bootctl)
            echo "/boot/EFI"
            ;;
    esac
}

# Check for a mounted /boot dir, and tries to mount it if specified by the user
BOOT_SUBDIR=$(_bootsubdir)
if [ ! -d "${BOOT_SUBDIR}" ]; then
    if [ "${MOUNT_BOOT}" == "yes" ]; then
        kinfo "Mounting /boot..."
        mount /boot || die
    fi
fi
if [ ! -d "${BOOT_SUBDIR}" ]; then
    kerror "${BOOT_MANAGER^} is not installed or /boot is not mounted."
fi

# die function
function die() {
    kerror "An error ocurred. Exiting."
}

# Copies the kernel configuration to the new kernel, runs oldconfig and compiles
# the kernel
function kernel_compile() {
    kinfo "Copying kernel configuration from ${KERNEL_CONFIG}..."
    /bin/cp -f "${KERNEL_CONFIG}" /usr/src/linux/.config &>> "${LOGFILE}" || die

    kinfo "Configuring kernel..."
    /bin/yes "" | make -C /usr/src/linux oldconfig &>> "${LOGFILE}" || die

    if [ "${UPDATE_KERNEL_CONFIG}" == "yes" ]; then
        kinfo "Updating kernel config..."
        /bin/cp -f /usr/src/linux/.config "${KERNEL_CONFIG}" || die
    fi

    SYNC_CHECK="/usr/src/linux/tools/objtool/sync-check.sh"
    if [ ! -x ${SYNC_CHECK} ]; then
        kinfo "Making sync-check.sh executable..."
        /bin/chmod 755 ${SYNC_CHECK} || die
    fi

    kinfo "Compiling kernel..."
    /usr/bin/make ${KERNEL_MAKEOPTS} -C /usr/src/linux &>> "${LOGFILE}" || die
}

# Deletes the kernel version files in Grub
function _delete_kernel_files_grub() {
    kinfo "Deleting kernel files with version ${KERNEL_VERSION} from /boot..."
    /bin/rm -f "/boot/config-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f "/boot/initrd-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f "/boot/System.map-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f "/boot/vmlinuz-${KERNEL_VERSION}" &>> "${LOGFILE}" || die
}

# Deletes the kernel version files in Bootctl
function _delete_kernel_files_bootctl() {
    kinfo "Deleting kernel files with version ${KERNEL_VERSION} from /boot..."
    /bin/rm -rf "/boot/${MACHINE_ID}/${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    /bin/rm -f "/boot/loader/entries/${MACHINE_ID}-${KERNEL_VERSION}.conf" &>> "${LOGFILE}" || die
}

# Deletes the kernel version modules
function _delete_lib_modules() {
    kinfo "Deleting kernel files with version ${KERNEL_VERSION} from /lib/modules..."
    /bin/rm -rf "/lib/modules/${KERNEL_VERSION}" &>> "${LOGFILE}" || die
}

# Deletes the kernel version files and modules
function _delete_kernel_files() {
    case "${BOOT_MANAGER}" in
        grub)
            _delete_kernel_files_grub
            ;;
        bootctl)
            _delete_kernel_files_bootctl
            ;;
    esac
    _delete_lib_modules
}

# Installs the kernel files for Grub
function _kernel_install_grub() {
    kinfo "Installing kernel..."
    make -C /usr/src/linux install &>> "${LOGFILE}" || die
    kinfo "The kernel was installed into /boot/vmlinuz-${KERNEL_VERSION}."
}

# Installs the kernel files for Bootctl
function _kernel_install_bootctl() {
    LOCATION="/boot/${MACHINE_ID}/${KERNEL_VERSION}/kernel"

    kinfo "Installing kernel..."
    /bin/mkdir -p "/boot/${MACHINE_ID}/${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    cp "/usr/src/linux/arch/x86/boot/bzImage" "${LOCATION}" &>> "${LOGFILE}" || die
    kinfo "The kernel was installed into ${LOCATION}."
}

# Installs the modules
function _install_modules() {
    kinfo "Installing modules..."
    make -C /usr/src/linux modules_install &>> "${LOGFILE}" || die
}

# Installs the kernel files and modules
function kernel_install() {
    _delete_kernel_files
    case "${BOOT_MANAGER}" in
        grub)
            _kernel_install_grub
            ;;
        bootctl)
            _kernel_install_bootctl
            ;;
    esac
    _install_modules
}

# Returns the correct initrd location
function _initrd_location() {
    case "${BOOT_MANAGER}" in
        grub)
            echo "/boot/initrd-${KERNEL_VERSION}"
            ;;
        bootctl)
            echo "/boot/${MACHINE_ID}/${KERNEL_VERSION}/initrd"
            ;;
    esac
}

# Returns the correct intel-ucode initramfs location
function _intel_ucode_location() {
    case "${BOOT_MANAGER}" in
        grub)
            echo "/boot/intel-ucode-${KERNEL_VERSION}"
            ;;
        bootctl)
            echo "/boot/${MACHINE_ID}/${KERNEL_VERSION}/intel-ucode"
            ;;
    esac
}

# Creates the initrd
function make_initrd() {
    if [ "${MODULES_REBUILD}" == "yes" ]; then
        kinfo "Recompiling modules..."
        /usr/bin/emerge -v @module-rebuild &>> "${LOGFILE}" || die
    fi

    LOCATION=$(_initrd_location)

    kinfo "Creating initrd..."
    if [ "${INCLUDES}" != "" ] || [ "${INCLUDE_FIRMWARE}" == "yes" ]; then
        INCLUDED="-I"

        for i in $(find /lib64/firmware -type f); do
            INCLUDED+=" ${i}"
        done

        for i in $(echo ${INCLUDES}); do
            INCLUDED+=" ${i}"
        done

        /usr/bin/dracut -f "${INCLUDED}" "${LOCATION}" "${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    else
        /usr/bin/dracut -f "${LOCATION}" "${KERNEL_VERSION}" &>> "${LOGFILE}" || die
    fi
    kinfo "The initrd was installed into ${LOCATION}."
}

# Updates grub
function _update_bootmanager_grub() {
    kinfo "Updating GRUB..."
    if [ "${MOUNT_BOOT_EFI}" == "yes" ]; then
        kinfo "Mounting EFI boot directory..."
        /bin/mountpoint -q  /boot/efi || /bin/mount /boot/efi
    fi
    /usr/sbin/grub-mkconfig -o "${GRUB_CONFIG_FILE}" &>> "${LOGFILE}" || die
}

# Updates bootctl
function _update_bootmanager_bootctl() {
    kinfo "Updating Bootctl..."
    if [ "${BOOTCTL_TITLE}" == "" ]; then
        BOOTCTL_TITLE="Linux"
    fi

    ENTRY="/boot/loader/entries/${MACHINE_ID}-${KERNEL_VERSION}.conf"
    KERNEL="/${MACHINE_ID}/${KERNEL_VERSION}/kernel"
    INITRD="/${MACHINE_ID}/${KERNEL_VERSION}/initrd"
    INTEL_UCODE="/${MACHINE_ID}/${KERNEL_VERSION}/intel-ucode"

    /usr/bin/printf "title        %s\n" "${BOOTCTL_TITLE}"         >  ${ENTRY}
    /usr/bin/printf "version      %s\n" "${KERNEL_VERSION}"      >> ${ENTRY}
    /usr/bin/printf "machine-id   %s\n" "${MACHINE_ID}"         >> ${ENTRY}
    /usr/bin/printf "linux        %s\n" "${KERNEL}"                >> ${ENTRY}
    /usr/bin/printf "initrd       %s\n" "${INITRD}"               >> ${ENTRY}
    /usr/bin/printf "options      %s\n" "${KERNEL_COMMAND_LINE}" >> ${ENTRY}
}

# Updates the boot manager
function update_bootmanager() {
    case "${BOOT_MANAGER}" in
        grub)
            _update_bootmanager_grub
            ;;
        bootctl)
            _update_bootmanager_bootctl
            ;;
    esac
}

# Get the exec name
EXEC_NAME=$(/usr/bin/basename "$0")

# Override configuration file with command line flags
for ARG in "$@"; do
    case "${ARG}" in
        --modules-rebuild)
            MODULES_REBUILD="yes"
            ;;
        --no-modules-rebuild)
            MODULES_REBUILD="no"
            ;;
        --update-kernel-config)
            UPDATE_KERNEL_CONFIG="yes"
            ;;
        --no-update-kernel-config)
            UPDATE_KERNEL_CONFIG="no"
            ;;
    esac
done

# Delete other (not current version) grub files
function _delete_other_files_grub() {
    for FILE in /boot/{config,initrd,System.map,vmlinuz}-*; do
        if [ "${FILE}" == "/boot/config-${KERNEL_VERSION}" ] ||
               [ "${FILE}" == "/boot/intel-ucode-${KERNEL_VERSION}" ] ||
               [ "${FILE}" == "/boot/initrd-${KERNEL_VERSION}" ] ||
               [ "${FILE}" == "/boot/System.map-${KERNEL_VERSION}" ] ||
               [ "${FILE}" == "/boot/vmlinuz-${KERNEL_VERSION}" ]; then
            continue
        fi
        kinfo "Deleting ${FILE}..."
        /bin/rm -f "${FILE}" &>> "${LOGFILE}" || die
    done
}

# Delete other (not current version) bootctl files
function _delete_other_files_bootctl() {
    for DIR in /boot/${MACHINE_ID}/*; do
        if [ "${DIR}" == "/boot/${MACHINE_ID}/${KERNEL_VERSION}" ]; then
            continue
        fi
        kinfo "Deleting ${DIR}..."
        /bin/rm -rf "${DIR}" &>> "${LOGFILE}" || die
    done
    for FILE in /boot/loader/entries/*; do
        if [ "${FILE}" == "/boot/loader/entries/${MACHINE_ID}-${KERNEL_VERSION}.conf" ]; then
            continue
        fi
        kinfo "Deleting ${FILE}..."
        /bin/rm -f "${FILE}" &>> "${LOGFILE}" || die
    done
}

# Clean files from other kernel versions
function clean() {
    for DIR in /usr/src/linux-* /lib/modules/*; do
        if [ ! -d "${DIR}" ]; then
            continue
        fi
        if [ "${DIR}" == "/usr/src/${KERNEL_DIR}" ]; then
            continue
        fi
        if [ "${DIR}" == "/lib/modules/${KERNEL_VERSION}" ]; then
            continue
        fi
        kinfo "Deleting ${DIR}..."
        /bin/rm -rf "${DIR}" &>> "${LOGFILE}" || die
    done
    case "${BOOT_MANAGER}" in
        grub)
            _delete_other_files_grub
            ;;
        bootctl)
            _delete_other_files_bootctl
            ;;
    esac
}

# "Main"
case "${EXEC_NAME}" in
    kerninst)
        kernel_compile
        kernel_install
        make_initrd
        update_bootmanager
        ;;
    kerninst-compile)
        kernel_compile
        ;;
    kerninst-install)
        kernel_install
        ;;
    kerninst-mkinitrd)
        make_initrd
        ;;
    kerninst-updatebm)
        update_bootmanager
        ;;
    kerninst-clean)
        clean
        ;;
    *)
        kerror "Invalid executable name."
        ;;
esac
